### ISSUE TITLE
[Easter Egg] Issue

### ISSUE THREAD

**Issue by DravenXD** [Spookybuddy/LC-Mods#3]
**Describe the bug**
A clear and concise description of what the bug is:
In version 56 of the game, thrown easter eggs will not explode. The eggs I used were ones I had collected and saved (exit game, load save) before using.

**To Reproduce**
Play on version 56 of the game and throw an egg. You may need to save, exit and reload the saved game.

**Comment by Spookybuddy** [comment]
A v62 update that fixes all issues is now available.
