### ISSUE TITLE
[Easter Egg] Missing Dependency

### ISSUE THREAD

**Issue by broken-usb** [Spookybuddy/LC-Mods#6]
**Describe the bug**
This mod requires you to have [Lethal Lib](https://thunderstore.io/c/lethal-company/p/Evaisa/LethalLib/) installed for it to work but you forgot to include it as a dependency on Thunderstore. The same "bug" will also happen with [Spike Trap Fixes](https://thunderstore.io/c/lethal-company/p/SpookyBuddy/SpikeTrapFixes/).

**To Reproduce**
Simply launch the game with this mod installed but without LethalLib.

**BepInEx Log**
`[Error  :   BepInEx] Could not load [EasterEggFixes 2.0.0] because it has missing dependencies: evaisa.lethallib`

**Comment by Spookybuddy** [comment]
Both mods have had the error fixed. They did not actually require LethalLib.
